<?php

function title_case_menu() {
    $items['title_case'] = array(
        'title' => 'Make Upper Case',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('title_case_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['title_case_success_page'] = array(
        'title' => 'Uppercase!',
        'page callback' => 'title_case_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function title_case_form() {
    $form['words'] = array(
        '#title' => 'Words',
        '#type' => 'textfield',
        '#description' => t('Please enter words to make uppercase.'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );

    return $form;
}

function title_case_form_submit($form, &$form_state) {
    $words = $form_state['values']['words'];
    $title_case = strtoupper($words);
    $_SESSION['title_case_output'] = $title_case;

    $form_state['redirect']= 'title_case_success_page';
}

function title_case_success() {
    $answer = $_SESSION['title_case_output'];
    return $answer;
}
